spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    url: ${DEV_DB_URL}
  jpa:
    show-sql: false
    properties:
      hibernate:
        highlight_sql: true